"""ajusta tabela apostas

Revision ID: 38d30c15fef2
Revises: adf191d6a1c3
Create Date: 2026-03-20 01:39:50.496193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '38d30c15fef2'
down_revision: Union[str, Sequence[str], None] = 'adf191d6a1c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sorteios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo', sa.Integer(), nullable=False),
    sa.Column('milhar', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['grupo'], ['bichos.grupo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sorteios_id'), 'sorteios', ['id'], unique=False)
    op.alter_column('apostas', 'numero',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apostas', 'numero',
               existing_type=sa.String(length=4),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.drop_index(op.f('ix_sorteios_id'), table_name='sorteios')
    op.drop_table('sorteios')
    # ### end Alembic commands ###
