"""cria tabela bichos

Revision ID: adf191d6a1c3
Revises: c535ec5034d9
Create Date: 2026-03-20 00:10:44.272201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'adf191d6a1c3'
down_revision: Union[str, Sequence[str], None] = 'c535ec5034d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bichos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grupo'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_bichos_id'), 'bichos', ['id'], unique=False)
    op.alter_column('usuarios', 'senha',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'senha',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_bichos_id'), table_name='bichos')
    op.drop_table('bichos')
    # ### end Alembic commands ###
