"""atualiza sorteio e aposta

Revision ID: ebcf1c1e6d57
Revises: 38d30c15fef2
Create Date: 2026-04-02 04:43:53.568866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebcf1c1e6d57'
down_revision: Union[str, Sequence[str], None] = '38d30c15fef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apostas', sa.Column('posicao_premiada', sa.Integer(), nullable=True))
    op.add_column('sorteios', sa.Column('rodada', sa.Integer(), nullable=False))
    op.add_column('sorteios', sa.Column('posicao', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_sorteios_rodada'), 'sorteios', ['rodada'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sorteios_rodada'), table_name='sorteios')
    op.drop_column('sorteios', 'posicao')
    op.drop_column('sorteios', 'rodada')
    op.drop_column('apostas', 'posicao_premiada')
    # ### end Alembic commands ###
